import Link from "next/link";
import { requireAdmin, isAdmin } from "@/lib/admin";
import { getSystemSettings, listAdminAudit, listOrders } from "@/lib/commerce";
import { listAdminUsers } from "@/lib/db";
import { getPlan, getUserEntitlements } from "@/lib/plans";
import { syncPayConfigured } from "@/lib/syncpay";
import { getPublicationCronHealth } from "@/lib/publication-cron-health";
import { reconcileOrderAction, suspendUserAction } from "@/app/actions/admin";
import { AdminSettings } from "@/components/admin-settings";
import styles from "@/components/commerce.module.css";
export const metadata = { title: "Administração", robots: { index: false, follow: false } };
const money = (cents: number) => (cents/100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const date = (value: number) => new Date(value).toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo", dateStyle: "short", timeStyle: "short" });
const labels: Record<string,string> = { creating: "Preparando", pending: "Pendente", paid: "Pago", failed: "Falhou", refunded: "Estornado", review: "Revisar" };
export default async function AdminPage({ searchParams }: { searchParams: Promise<{ aba?: string; mes?: string }> }) {
  await requireAdmin(); const query = await searchParams;
  const tabs = [{ id:"dashboard",name:"Dashboard" },{ id:"pedidos",name:"Pedidos" },{ id:"usuarios",name:"Usuários" },{ id:"calendario",name:"Calendário" },{ id:"configuracoes",name:"Configurações" }];
  const tab = tabs.some(t=>t.id===query.aba) ? query.aba! : "dashboard";
  const [orders, users, settings, audit, cronHealth] = await Promise.all([listOrders(), listAdminUsers(), getSystemSettings(), tab === "configuracoes" ? listAdminAudit() : Promise.resolve([]), tab === "dashboard" ? getPublicationCronHealth().catch(() => null) : Promise.resolve(undefined)]);
  const paid = orders.filter(o=>o.status === "paid"); const usersById = new Map(users.map(u=>[u.id,u]));
  const selectedMonth = /^\d{4}-(0[1-9]|1[0-2])$/.test(query.mes || "") ? query.mes! : new Intl.DateTimeFormat("sv-SE", { timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit" }).format(new Date());
  const [year,month] = selectedMonth.split("-").map(Number); const days = new Date(year,month,0).getDate(); const offset = new Date(year,month-1,1).getDay();
  const calendar = paid.filter(o=>new Date(o.paidAt ?? o.createdAt).toLocaleDateString("sv-SE", {timeZone:"America/Sao_Paulo"}).startsWith(selectedMonth));
  const connections = [{label:"Higgsfield", ready:!!process.env.HF_API_KEY},{label:"fal.ai",ready:!!process.env.FAL_KEY},{label:"Armazenamento de mídia",ready:!!process.env.BLOB_READ_WRITE_TOKEN},{label:"Sync Pay · credenciais e assinatura",ready:syncPayConfigured()},{label:"Instagram · credenciais",ready:!!process.env.INSTAGRAM_APP_ID&&!!process.env.INSTAGRAM_APP_SECRET},{label:"Proteção dos tokens sociais",ready:!!process.env.SOCIAL_TOKEN_SECRET},{label:"Agendamento automático",ready:!!process.env.CRON_SECRET&&process.env.PUBLICATION_CRON_CONFIGURED==="true"}];
  return <div className={styles.wrap}><header className="page-header"><h1>PAINEL <span>ADMIN</span></h1><p>Acompanhe a operação, os clientes e os pagamentos.</p></header><nav className={styles.tabs} aria-label="Administração">{tabs.map(t=><Link href={`/app/admin?aba=${t.id}`} key={t.id} aria-current={tab===t.id?"page":undefined}>{t.name}</Link>)}</nav>
    {tab==="dashboard" && <><div className={styles.metrics}><div className={styles.metric}><span>Vendas confirmadas</span><strong>{money(paid.reduce((sum,o)=>sum+o.amountCents,0))}</strong></div><div className={styles.metric}><span>Pedidos pagos</span><strong>{paid.length}</strong></div><div className={styles.metric}><span>Clientes cadastrados</span><strong>{users.length}</strong></div><div className={styles.metric}><span>Aguardando pagamento</span><strong>{orders.filter(o=>o.status==="pending").length}</strong></div></div><section className={styles.panel}><h2>Operação</h2><ul className={styles.checks}>{connections.map(c=><li key={c.label}><span>{c.label}</span><strong>{c.ready ? "Configurado" : "Pendente"}</strong></li>)}</ul><p className={styles.muted}>Configuração presente não substitui teste externo. Instagram depende de permissão, vínculo da conta e aprovação da Meta. Preços atuais são rascunhos; a venda só fica disponível com o gateway configurado.</p></section><p className={styles.muted}>Visão dos últimos 500 pedidos e 500 usuários. Valores brutos, sem taxas do gateway. Nenhum faturamento de exemplo é incluído.</p></>}
    {tab === "dashboard" && <section className={styles.panel}>
      <h2>Execuções do agendador</h2>
      {cronHealth ? <>
        <ul className={styles.checks}>
          <li><span>Último início autenticado</span><strong>{date(cronHealth.lastStartedAt)}</strong></li>
          <li><span>Última execução concluída</span><strong>{cronHealth.lastSucceededAt ? date(cronHealth.lastSucceededAt) : "Ainda não registrada"}</strong></li>
          <li><span>Última falha ou tempo excedido</span><strong>{cronHealth.lastErrorAt ? date(cronHealth.lastErrorAt) : "Nenhuma registrada"}</strong></li>
        </ul>
        {cronHealth.lastFinishedRunId !== cronHealth.lastRunId && <p className={styles.muted}>{Date.now() - cronHealth.lastStartedAt > 60_000 ? "A última execução não registrou sua conclusão." : "A última execução está em andamento."}</p>}
      </> : <p className={styles.muted}>{cronHealth === null ? "Não foi possível consultar o registro de execuções agora." : "Nenhuma execução autenticada registrada até agora."}</p>}
      <p className={styles.muted}>Horários de Brasília. O início confirma a chamada autenticada; a conclusão confirma que a consulta e o processamento da fila terminaram. Confira o resultado de cada publicação em Publicar.</p>
    </section>}
    {tab==="pedidos" && <section className={styles.panel}><h2>Pedidos</h2><div className={styles.tableScroll}><table><thead><tr><th>Cliente</th><th>Produto</th><th>Valor</th><th>Status</th><th>Data</th><th>Referência</th><th/></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{usersById.get(o.userId)?.email ?? o.userId}</td><td>{o.kind === "credits" ? `${o.credits.toLocaleString("pt-BR")} créditos` : getPlan(o.planId)?.name}</td><td>{money(o.amountCents)}</td><td>{labels[o.status]}</td><td>{date(o.createdAt)}</td><td title={o.id}>{o.referenceId ?? o.id}</td><td>{o.referenceId && o.status!=="refunded" && <form action={reconcileOrderAction}><input type="hidden" name="orderId" value={o.id}/><button className="btn btn-ghost">Conferir no gateway</button></form>}</td></tr>)}</tbody></table>{!orders.length&&<p className={styles.muted}>Nenhum pedido até agora.</p>}</div></section>}
    {tab==="usuarios" && <section className={styles.panel}><h2>Usuários</h2><div className={styles.tableScroll}><table><thead><tr><th>Nome</th><th>E-mail</th><th>Créditos</th><th>Plano</th><th>Cadastro</th><th>Status</th><th/></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.credits.toLocaleString("pt-BR")}</td><td>{getPlan(getUserEntitlements(u).planId)?.name ?? "Sem plano ativo"}</td><td>{date(u.createdAt)}</td><td>{isAdmin(u)?"Administrador":u.suspendedAt?"Suspenso":"Ativo"}</td><td>{!isAdmin(u)&&<form action={suspendUserAction}><input type="hidden" name="userId" value={u.id}/><input type="hidden" name="suspended" value={u.suspendedAt?"false":"true"}/><button className="btn btn-ghost">{u.suspendedAt?"Reativar":"Suspender"}</button></form>}</td></tr>)}</tbody></table></div></section>}
    {tab==="calendario" && <section className={styles.panel}><h2>Calendário de vendas</h2><form className={styles.form} method="get"><input type="hidden" name="aba" value="calendario"/><label>Mês<input name="mes" type="month" defaultValue={selectedMonth} min="2026-01" max="2100-12"/></label><button className="btn btn-ghost">Consultar mês</button></form><p>{calendar.length} vendas · {money(calendar.reduce((s,o)=>s+o.amountCents,0))}</p><div className={styles.calendar}>{["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"].map(d=><span key={d}>{d}</span>)}{Array.from({length:offset},(_,i)=><div key={`empty${i}`}/>)}{Array.from({length:days},(_,i)=>{const day=i+1;const key=`${selectedMonth}-${String(day).padStart(2,"0")}`;const sales=calendar.filter(o=>new Date(o.paidAt??o.createdAt).toLocaleDateString("sv-SE",{timeZone:"America/Sao_Paulo"})===key);return <div className={styles.day} key={day}>{day}{sales.length>0&&<><strong>{money(sales.reduce((s,o)=>s+o.amountCents,0))}</strong><span>{sales.length} venda(s)</span></>}</div>;})}</div></section>}
    {tab==="configuracoes" && <><section className={styles.panel}><AdminSettings settings={settings}/></section><section className={styles.panel}><h2>Registro administrativo</h2><div className={styles.tableScroll}><table><thead><tr><th>Data</th><th>Ação</th><th>Alvo</th></tr></thead><tbody>{audit.map(a=><tr key={a.id}><td>{date(a.createdAt)}</td><td>{a.action}</td><td>{a.targetId}</td></tr>)}</tbody></table>{!audit.length&&<p className={styles.muted}>Nenhuma alteração administrativa registrada.</p>}</div></section></>}
  </div>;
}
